// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: cardService.proto

package Server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UNITS
type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{0}
}

func (x *Name) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hello string `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field            int32    `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	Answers          []string `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	IncorrectAnswers []string `protobuf:"bytes,3,rep,name=incorrectAnswers,proto3" json:"incorrectAnswers,omitempty"`
	Explanation      string   `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *Answer) Reset() {
	*x = Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{2}
}

func (x *Answer) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

func (x *Answer) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *Answer) GetIncorrectAnswers() []string {
	if x != nil {
		return x.IncorrectAnswers
	}
	return nil
}

func (x *Answer) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type FlashCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string    `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Title    string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text     string    `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Answers  []*Answer `protobuf:"bytes,5,rep,name=answers,proto3" json:"answers,omitempty"`
	Media    []string  `protobuf:"bytes,6,rep,name=media,proto3" json:"media,omitempty"`
	Lang     []string  `protobuf:"bytes,7,rep,name=lang,proto3" json:"lang,omitempty"`
	Topics   []string  `protobuf:"bytes,8,rep,name=topics,proto3" json:"topics,omitempty"`
	Date     string    `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *FlashCard) Reset() {
	*x = FlashCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashCard) ProtoMessage() {}

func (x *FlashCard) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashCard.ProtoReflect.Descriptor instead.
func (*FlashCard) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{3}
}

func (x *FlashCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlashCard) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FlashCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FlashCard) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FlashCard) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *FlashCard) GetMedia() []string {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *FlashCard) GetLang() []string {
	if x != nil {
		return x.Lang
	}
	return nil
}

func (x *FlashCard) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *FlashCard) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Deck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId      string   `protobuf:"bytes,1,opt,name=deckId,proto3" json:"deckId,omitempty"`
	Title       string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Username    string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CardAuthors []string `protobuf:"bytes,4,rep,name=cardAuthors,proto3" json:"cardAuthors,omitempty"`
	Topics      []string `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty"`
	CardIds     []string `protobuf:"bytes,6,rep,name=cardIds,proto3" json:"cardIds,omitempty"`
}

func (x *Deck) Reset() {
	*x = Deck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deck) ProtoMessage() {}

func (x *Deck) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deck.ProtoReflect.Descriptor instead.
func (*Deck) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{4}
}

func (x *Deck) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *Deck) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Deck) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Deck) GetCardAuthors() []string {
	if x != nil {
		return x.CardAuthors
	}
	return nil
}

func (x *Deck) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Deck) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

type CreateFlashCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *FlashCard `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *CreateFlashCardReq) Reset() {
	*x = CreateFlashCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlashCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlashCardReq) ProtoMessage() {}

func (x *CreateFlashCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlashCardReq.ProtoReflect.Descriptor instead.
func (*CreateFlashCardReq) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFlashCardReq) GetCard() *FlashCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type CreateFlashCardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateFlashCardRes) Reset() {
	*x = CreateFlashCardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlashCardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlashCardRes) ProtoMessage() {}

func (x *CreateFlashCardRes) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlashCardRes.ProtoReflect.Descriptor instead.
func (*CreateFlashCardRes) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{6}
}

func (x *CreateFlashCardRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserCardsByUsernameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username     string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Page         int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	LimitPerPage int32  `protobuf:"varint,3,opt,name=limitPerPage,proto3" json:"limitPerPage,omitempty"`
}

func (x *GetUserCardsByUsernameReq) Reset() {
	*x = GetUserCardsByUsernameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCardsByUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsByUsernameReq) ProtoMessage() {}

func (x *GetUserCardsByUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsByUsernameReq.ProtoReflect.Descriptor instead.
func (*GetUserCardsByUsernameReq) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserCardsByUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserCardsByUsernameReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserCardsByUsernameReq) GetLimitPerPage() int32 {
	if x != nil {
		return x.LimitPerPage
	}
	return 0
}

type GetUserCardsByUsernameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*FlashCard `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *GetUserCardsByUsernameRes) Reset() {
	*x = GetUserCardsByUsernameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCardsByUsernameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsByUsernameRes) ProtoMessage() {}

func (x *GetUserCardsByUsernameRes) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsByUsernameRes.ProtoReflect.Descriptor instead.
func (*GetUserCardsByUsernameRes) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserCardsByUsernameRes) GetCards() []*FlashCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type CreateDeckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deck *Deck `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
}

func (x *CreateDeckReq) Reset() {
	*x = CreateDeckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeckReq) ProtoMessage() {}

func (x *CreateDeckReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeckReq.ProtoReflect.Descriptor instead.
func (*CreateDeckReq) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{9}
}

func (x *CreateDeckReq) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type CreateDeckRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deck *Deck `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
}

func (x *CreateDeckRes) Reset() {
	*x = CreateDeckRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeckRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeckRes) ProtoMessage() {}

func (x *CreateDeckRes) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeckRes.ProtoReflect.Descriptor instead.
func (*CreateDeckRes) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDeckRes) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type EditCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId string     `protobuf:"bytes,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	Card   *FlashCard `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *EditCardReq) Reset() {
	*x = EditCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCardReq) ProtoMessage() {}

func (x *EditCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCardReq.ProtoReflect.Descriptor instead.
func (*EditCardReq) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{11}
}

func (x *EditCardReq) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *EditCardReq) GetCard() *FlashCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type EditCardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *FlashCard `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *EditCardRes) Reset() {
	*x = EditCardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCardRes) ProtoMessage() {}

func (x *EditCardRes) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCardRes.ProtoReflect.Descriptor instead.
func (*EditCardRes) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{12}
}

func (x *EditCardRes) GetCard() *FlashCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type EditDeckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId string `protobuf:"bytes,1,opt,name=deckId,proto3" json:"deckId,omitempty"`
	Deck   *Deck  `protobuf:"bytes,2,opt,name=deck,proto3" json:"deck,omitempty"`
}

func (x *EditDeckReq) Reset() {
	*x = EditDeckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditDeckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditDeckReq) ProtoMessage() {}

func (x *EditDeckReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditDeckReq.ProtoReflect.Descriptor instead.
func (*EditDeckReq) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{13}
}

func (x *EditDeckReq) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *EditDeckReq) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type EditDeckRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deck *Deck `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
}

func (x *EditDeckRes) Reset() {
	*x = EditDeckRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditDeckRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditDeckRes) ProtoMessage() {}

func (x *EditDeckRes) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditDeckRes.ProtoReflect.Descriptor instead.
func (*EditDeckRes) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{14}
}

func (x *EditDeckRes) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type GetCardsByDeckIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId string `protobuf:"bytes,1,opt,name=deckId,proto3" json:"deckId,omitempty"`
}

func (x *GetCardsByDeckIdReq) Reset() {
	*x = GetCardsByDeckIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCardsByDeckIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByDeckIdReq) ProtoMessage() {}

func (x *GetCardsByDeckIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByDeckIdReq.ProtoReflect.Descriptor instead.
func (*GetCardsByDeckIdReq) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{15}
}

func (x *GetCardsByDeckIdReq) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type GetCardsByDeckIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*FlashCard `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *GetCardsByDeckIdRes) Reset() {
	*x = GetCardsByDeckIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardService_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCardsByDeckIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByDeckIdRes) ProtoMessage() {}

func (x *GetCardsByDeckIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_cardService_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByDeckIdRes.ProtoReflect.Descriptor instead.
func (*GetCardsByDeckIdRes) Descriptor() ([]byte, []int) {
	return file_cardService_proto_rawDescGZIP(), []int{16}
}

func (x *GetCardsByDeckIdRes) GetCards() []*FlashCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_cardService_proto protoreflect.FileDescriptor

var file_cardService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x1d, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x86,
	0x01, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x6e, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x10, 0x69, 0x6e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6c,
	0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xda, 0x01, 0x0a, 0x09, 0x46, 0x6c, 0x61, 0x73,
	0x68, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x04, 0x44, 0x65, 0x63, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61,
	0x72, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x22, 0x34, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x50, 0x65, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x2a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x52, 0x04, 0x64,
	0x65, 0x63, 0x6b, 0x22, 0x2a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x52, 0x04, 0x64, 0x65, 0x63, 0x6b, 0x22,
	0x45, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x2d, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x40, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x44, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x04,
	0x64, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x63,
	0x6b, 0x52, 0x04, 0x64, 0x65, 0x63, 0x6b, 0x22, 0x28, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x44,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x52, 0x04, 0x64, 0x65, 0x63,
	0x6b, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x44,
	0x65, 0x63, 0x6b, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x6b,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64,
	0x22, 0x37, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x44, 0x65,
	0x63, 0x6b, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x32, 0xf5, 0x02, 0x0a, 0x0b, 0x43, 0x61,
	0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x53, 0x61, 0x79,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x05, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x06, 0x2e, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x3f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x72, 0x64, 0x12, 0x13, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x0c, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x08, 0x45,
	0x64, 0x69, 0x74, 0x44, 0x65, 0x63, 0x6b, 0x12, 0x0c, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x44, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x44, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x44,
	0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x42, 0x79, 0x44, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x44, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x42, 0x15, 0x5a, 0x13, 0x63, 0x61, 0x72, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cardService_proto_rawDescOnce sync.Once
	file_cardService_proto_rawDescData = file_cardService_proto_rawDesc
)

func file_cardService_proto_rawDescGZIP() []byte {
	file_cardService_proto_rawDescOnce.Do(func() {
		file_cardService_proto_rawDescData = protoimpl.X.CompressGZIP(file_cardService_proto_rawDescData)
	})
	return file_cardService_proto_rawDescData
}

var file_cardService_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cardService_proto_goTypes = []interface{}{
	(*Name)(nil),                      // 0: Name
	(*Hello)(nil),                     // 1: Hello
	(*Answer)(nil),                    // 2: Answer
	(*FlashCard)(nil),                 // 3: FlashCard
	(*Deck)(nil),                      // 4: Deck
	(*CreateFlashCardReq)(nil),        // 5: CreateFlashCardReq
	(*CreateFlashCardRes)(nil),        // 6: CreateFlashCardRes
	(*GetUserCardsByUsernameReq)(nil), // 7: GetUserCardsByUsernameReq
	(*GetUserCardsByUsernameRes)(nil), // 8: GetUserCardsByUsernameRes
	(*CreateDeckReq)(nil),             // 9: CreateDeckReq
	(*CreateDeckRes)(nil),             // 10: CreateDeckRes
	(*EditCardReq)(nil),               // 11: EditCardReq
	(*EditCardRes)(nil),               // 12: EditCardRes
	(*EditDeckReq)(nil),               // 13: EditDeckReq
	(*EditDeckRes)(nil),               // 14: EditDeckRes
	(*GetCardsByDeckIdReq)(nil),       // 15: GetCardsByDeckIdReq
	(*GetCardsByDeckIdRes)(nil),       // 16: GetCardsByDeckIdRes
}
var file_cardService_proto_depIdxs = []int32{
	2,  // 0: FlashCard.answers:type_name -> Answer
	3,  // 1: CreateFlashCardReq.card:type_name -> FlashCard
	3,  // 2: GetUserCardsByUsernameRes.cards:type_name -> FlashCard
	4,  // 3: CreateDeckReq.deck:type_name -> Deck
	4,  // 4: CreateDeckRes.deck:type_name -> Deck
	3,  // 5: EditCardReq.card:type_name -> FlashCard
	3,  // 6: EditCardRes.card:type_name -> FlashCard
	4,  // 7: EditDeckReq.deck:type_name -> Deck
	4,  // 8: EditDeckRes.deck:type_name -> Deck
	3,  // 9: GetCardsByDeckIdRes.cards:type_name -> FlashCard
	0,  // 10: CardService.SayHello:input_type -> Name
	5,  // 11: CardService.CreateUserFlashCard:input_type -> CreateFlashCardReq
	9,  // 12: CardService.CreateDeck:input_type -> CreateDeckReq
	11, // 13: CardService.EditCard:input_type -> EditCardReq
	13, // 14: CardService.EditDeck:input_type -> EditDeckReq
	7,  // 15: CardService.GetCardsByUsername:input_type -> GetUserCardsByUsernameReq
	15, // 16: CardService.GetCardsByDeckId:input_type -> GetCardsByDeckIdReq
	1,  // 17: CardService.SayHello:output_type -> Hello
	6,  // 18: CardService.CreateUserFlashCard:output_type -> CreateFlashCardRes
	10, // 19: CardService.CreateDeck:output_type -> CreateDeckRes
	12, // 20: CardService.EditCard:output_type -> EditCardRes
	14, // 21: CardService.EditDeck:output_type -> EditDeckRes
	8,  // 22: CardService.GetCardsByUsername:output_type -> GetUserCardsByUsernameRes
	16, // 23: CardService.GetCardsByDeckId:output_type -> GetCardsByDeckIdRes
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cardService_proto_init() }
func file_cardService_proto_init() {
	if File_cardService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cardService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlashCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlashCardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCardsByUsernameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCardsByUsernameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeckRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditDeckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditDeckRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCardsByDeckIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardService_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCardsByDeckIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cardService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cardService_proto_goTypes,
		DependencyIndexes: file_cardService_proto_depIdxs,
		MessageInfos:      file_cardService_proto_msgTypes,
	}.Build()
	File_cardService_proto = out.File
	file_cardService_proto_rawDesc = nil
	file_cardService_proto_goTypes = nil
	file_cardService_proto_depIdxs = nil
}
